name: Update Version Hash
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          VERSION_HASH=$(git describe --tags --always)
          echo "const version_hash = '${VERSION_HASH}';" > js/version-hash.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add js/version-hash.js
          git commit -m "Updated version [workflow]"
          git push
